version: '3.4'

services:
  api:
    container_name: 'email-api'
    image: node:16
    user: node
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      STAGE: 'dev'
      PORT: 8080
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
      SMTP_USERNAME: teste@teste.com
      SMTP_PASSWORD: dev
    working_dir: "/app"
    command: bash -c "npm install && npm run dev"
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # SMTP Server
      - 8025:8025 # Web UI

